[mcp_servers.context7]
args = ["-y", "@upstash/context7-mcp", "--api-key", "ctx7sk-4146be3f-9b57-4184-97c8-ada9ed30b03c"]
command = "npx"

[mcp_servers.supabase]
command = "npx"
args = ["-y", "@supabase/mcp-server-supabase@latest", "--project-ref=junhhrcxizltevsdiwlw"]
env = { API_KEY = "sbp_42e3d70c75dc0312c2bf03a7875fe3ab5d618" }


